### ISSUE TITLE
failed to start node server on ubuntu 18.04.03 with node v10.16.2 and npm 6.9.0 

### ISSUE THREAD

**Issue by Bastika07** [botgram/shell-bot#14]

**Comment by Bastika07** [comment]
node server.js 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build/Release/termios.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mc/shell-bot/node_modules/node-termios/lib/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Bastika07** [comment]
third time reinstalling nodejs and cloning the repository and now it´s working
