### ISSUE TITLE
Error using the "node server" command in the termux

### ISSUE THREAD

**Issue by HitaloKun** [botgram/shell-bot#18]
**I ran the npm install command and then the node server but I get this error:** 

```
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/etc/shells'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at getShells (/data/data/com.termux/files/home/shell-bot/lib/utils.js:154:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/shell-bot/lib/utils.js:167:14)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/shells'
}
```

**Comment by An0nUD4Y** [comment]
Same Error...

**Comment by avissian** [comment]
What shell do you want to see in termux? This is not a full Linux

**Comment by HitaloKun** [comment]
Problem solved, shell-bot is fully functional in Termux.
