### ISSUE TITLE
 Cannot read property 'SOCKET' of undefined

### ISSUE THREAD

**Issue by LFG2019347** [botgram/shell-bot#27]
Hello, when I execute `/run < command >`, the bot will report an error. To execute another command, such as `/cd`, the bot works normally.
```
/root/shell-bot/node_modules/node-pty/lib/unixTerminal.js:269
        var handle = new Pipe(constants.SOCKET);
                                       ^

TypeError: Cannot read property 'SOCKET' of undefined
    at new PipeSocket (/root/shell-bot/node_modules/node-pty/lib/unixTerminal.js:269:40)
    at new UnixTerminal (/root/shell-bot/node_modules/node-pty/lib/unixTerminal.js:94:25)
    at Object.spawn (/root/shell-bot/node_modules/node-pty/lib/index.js:28:12)
    at new Command (/root/shell-bot/lib/command.js:22:18)
    at Bot.<anonymous> (/root/shell-bot/server.js:192:25)
    at Bot.<anonymous> (/root/shell-bot/node_modules/botgram/lib/message.js:87:22)
    at HandlerQueue.callHandler (/root/shell-bot/node_modules/botgram/lib/message.js:63:29)
    at Bot.<anonymous> (/root/shell-bot/node_modules/botgram/lib/message.js:86:43)
    at HandlerQueue.callHandler (/root/shell-bot/node_modules/botgram/lib/message.js:63:29)
    at Bot.<anonymous> (/root/shell-bot/node_modules/botgram/lib/message.js:86:43)
```

**Comment by mildsunrise** [comment]
are you sure that `npm install` finished correctly?

**Comment by LFG2019347** [comment]
> are you sure that `npm install` finished correctly?

Yes, the` npm install` process is normal. In addition to the `/run command`, other commands can be executed

**Comment by LFG2019347** [comment]
> are you sure that `npm install` finished correctly?

I install the bot on another computer, all  commands can be executed. It may be a problem with my computer environment.

**Comment by LFG2019347** [comment]
> are you sure that `npm install` finished correctly?

It may be because the nodejs version（V6） is too low. After upgrading the nodejs version, the bot can run normally
