### ISSUE TITLE
[Bug]Not working since few day

### ISSUE THREAD

**Issue by billouetaudrey** [botgram/shell-bot#58]
Hello,

Since few day, my bot stop working, can you help me?

```
`billou@billou-serveur:~/Téléchargements/Serveur/Bot Desktop/shell-bot$ shellbot innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/unixTerminal.js
- /home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/index.js
- /home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/lib/command.js
- /home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/unixTerminal.js',
    '/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/index.js',
    '/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/lib/command.js',
    '/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/server.js'
  ]
}
/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: libnode.so.64: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/billou/Téléchargements/Serveur/Bot Desktop/shell-bot/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)`
```

**Comment by billouetaudrey** [comment]
Fixed ! 

sudo npm install -g npm && npm clean-install
