### ISSUE TITLE
Cannot find module 'botgram'

### ISSUE THREAD

**Issue by KuroViet97** [botgram/shell-bot#9]
Hello, 

I've got an issue while trying to run `node server`, any idea how to fix it?

> module.js:549
    throw err;
    ^

Error: Cannot find module 'botgram'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/chatbox/shell-bot/server.js:9:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by avissian** [comment]
What version of nodejs? What returns on `npm install botgram`?
